name: testing github actions

on:
  push :
    branches:
      - master

permissions:
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: installing node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: install dependencies
        run: npm install

      - name: make the build 
        run: npm run build 

      - name: upload the prod ready build files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: deploy to gh pages
        uses: actions/deploy-pages@v4
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: download the artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name : final-build
  #         path: ./dist
  #
  #     - name: deploy to gh pages
  #       uses: actions/deploy-pages@v4
  #
